# This is the network config written by 'console_conf'
network:
  ethernets:
    eth0:
      addresses: []
      dhcp4: true
  version: 2
  wifis:
    wlan0:
      access-points:
        Airlink: {password: plot66@321}
      addresses: []
      dhcp4: true
